modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/millenaire/millenaire-revived/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
credits="Original Millenaire by Kinniken, Revival by the Millenaire Team"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="https://github.com/millenaire/millenaire-revived"

[[dependencies.millenaire]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.millenaire]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
